### ISSUE TITLE
Missing "=" in style block

### ISSUE THREAD

**Issue by troeglazov** [linslin/phploc-xmlToHtmlReport#1]
Hello, thank you for your tool, it's very useful, but I've noticed some kind of bug.
Missing "=" breaks layout in my Jenkins.
http://storage3.static.itmages.com/i/16/0701/h_1467348359_4428437_44d98b500f.png
Thanks.
Kind Regards.

**Comment by linslin** [comment]
Hi @troeglazov 

thanks for your report. We will fix that!

Lin

**Comment by kala4ek** [comment]
Hi, I've created simple PR for it.
https://github.com/linslin/phploc-xmlToHtmlReport/pull/2

**Comment by linslin** [comment]
Thanks! Version 0.0.2 is ready for use: https://packagist.org/packages/linslin/phploc-xmltohtmlreport
